INSERT INTO `mqtt_topics` (`id`, `user_id`, `order`, `log_enabled`, `name`, `topic`, `direction`, `type`, `publish_word`, `word_min_value`, `word_max_value`, `publish_icon_on`, `publish_icon_off`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 0, 'lamp', 'home_y20', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(2, 1, 2, 0, 'lamp', 'home_y43', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(3, 1, 3, 0, 'lamp', 'home_y114', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(4, 1, 4, 0, 'temp', 'home_temp1', 'publish', 'word', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(5, 1, 5, 0, 'temp', 'home_temp4', 'publish', 'word', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(6, 1, 6, 0, 'lamp', 'tara_y20', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(7, 1, 7, 0, 'lamp', 'tara_y22', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(8, 1, 8, 0, 'lamp', 'tara_y23', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(9, 1, 9, 0, 'lamp', 'tara_y25', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(10, 1,10, 0, 'lamp', 'tara_y50', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(11, 1,11, 0, 'lamp', 'tara_y55', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(12, 1,12, 0, 'temp', 'tara_temp1', 'publish', 'word', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(13, 1, 13, 0, 'temp', 'tara_temp2', 'publish', 'word', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(14, 1, 14, 0, 'lamp', 'tara_sendy20', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(15, 1, 15, 0, 'lamp', 'tara_sendy22', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(16, 1, 16, 0, 'lamp', 'tara_sendy23', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(17, 1, 17, 0, 'lamp', 'tara_sendy25', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(18, 1, 18, 0, 'lamp', 'tara_sendy55', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(19, 1, 19, 0, 'lamp', 'tara_sendy57', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(20, 1, 20, 0, 'lamp', 'tara_sendy50', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(21, 1, 21, 0, 'lamp', 'home_sendy20', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(22, 1, 22, 0, 'lamp', 'home_sendy43', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(23, 1, 23, 0, 'lamp', 'home_sendy114', 'subscribe', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL),
(24, 1, 24, 0, 'temp', 'noori_d20', 'publish', 'bit', 'number', NULL, NULL, NULL, NULL, 1, NULL, NULL);
